import Head from "next/head";
import { Fragment } from "react";
import { MainLayout } from "../layouts";
import {
  HeroSection,
  NewsSection,
  ServicesSection,
} from "../components/blocks/main";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Avero</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout primary>
        <HeroSection />
        <ServicesSection />
        <NewsSection />
      </MainLayout>
    </Fragment>
  );
}
